Dockerfile
docker/pretalx.bash
src/pretalx/settings.py
src/requirements/production.txt

First Dockerfile, untested as docker is not working on my laptop atm.

First untested docker files

---

doc/install/simple_docker.rst

so it complies with the complete installation instructions

[doc] fix mapping of redis socket

---

src/pretalx/orga/views/settings.py

Fixes #73.
Please refer to the issue for details :)

[orga] display a friendy message when the user deletes a room, which is in use

---

src/setup.py

fix pylama warnings for setup.py

---

src/pretalx/agenda/templates/agenda/base.html
src/pretalx/agenda/templates/agenda/talk.html

This addresses #122, but does not fix it completely.

[agenda] add very basic meta tags for facebook and twitter

---

src/pretalx/common/templates/common/base.html
src/pretalx/orga/templates/orga/base.html

pretalx has got a fancy website. link to it! :)

[common][orga] link to pretalx.org instead of the github page

---

doc/install/configure.rst
doc/install/index.rst
src/pretalx.example.cfg
src/pretalx/settings.py

[WIP] Add proper settings handling

---

src/pretalx/common/__init__.py
src/pretalx/settings.py

Fixes #188.
Just by running `/manage.py runserver`. This should probably be tested automatically, but I'd need a few pointers on how to do it.

regenerate custom css at start

---

src/pretalx/agenda/templates/agenda/talk.html
src/pretalx/agenda/urls.py
src/pretalx/agenda/views/schedule.py
src/pretalx/schedule/models/slot.py
src/pretalx/submission/models/submission.py
src/tests/functional/agenda/test_schedule_export.py

Improve #67 – add an ical export for single events and extract necessary methods for further steps.

ical export

---

src/pretalx/common/mail.py
src/pretalx/mail/models.py
src/pretalx/mail/templates/mail/mailwrapper.html
src/pretalx/orga/views/settings.py
src/requirements/production.txt
src/setup.py

Send HTML/multipart emails

---

src/pretalx/common/middleware.py
src/pretalx/orga/views/auth.py
src/tests/functional/orga/test_auth.py

Keep queryparams when logging in

---

src/pretalx/orga/__init__.py
src/pretalx/orga/forms/cfp.py
src/pretalx/orga/forms/event.py
src/pretalx/orga/forms/review.py
src/pretalx/orga/forms/submission.py
src/pretalx/orga/phrases.py
src/pretalx/orga/templates/orga/schedule/index.html
src/pretalx/schedule/forms.py
src/pretalx/settings.py

[orga] Use placeholders in forms

---

src/pretalx/common/middleware.py
src/pretalx/orga/templates/orga/base.html
src/pretalx/orga/templates/orga/review/dashboard.html
src/pretalx/orga/views/review.py
src/tests/functional/conftest.py
src/tests/functional/orga/test_access.py
src/tests/functional/orga/test_auth.py

Improve review evaluation

---

src/pretalx/orga/templates/orga/speaker/list.html
src/pretalx/orga/views/speaker.py
src/pretalx/person/models/profile.py
src/tests/functional/orga/test_speaker.py

Adds pagination, talk count, and fairly easy extendability.

[orga] Improve speaker view

---

src/pretalx/event/models/event.py
src/tests/functional/orga/test_settings.py

[tests] Add tests for invitation views

---

doc/contribute/setup.rst
doc/install/configure.rst
doc/install/index.rst
doc/install/simple_manual.rst
src/pretalx.example.cfg
src/pretalx/common/management/commands/rebuild.py
src/pretalx/settings.py

Add celery settings and docs

---

src/pretalx/orga/templates/orga/submission/review.html
src/pretalx/orga/views/review.py
src/pretalx/submission/permissions.py
src/tests/functional/orga/test_review.py

[orga] Prevent reviews of decided submissions to be edited

---

src/pretalx/agenda/templates/agenda/talk.html
src/tests/functional/agenda/test_agenda_schedule.py

We kind of broke the talk view in [a large change](https://github.com/pretalx/pretalx/commit/8a50da2b18a35823c8622946c4f67da7671978c0#diff-5bb5858356c06c2915ec52efbd571246L219). This fixes it and adds a bunch of tests.

[agenda] fix talk detail view and add a bunch of tests

---

src/pretalx/cfp/forms/auth.py
src/pretalx/cfp/templates/cfp/event/login.html
src/pretalx/cfp/templates/cfp/event/recover.html
src/pretalx/cfp/templates/cfp/event/submission_user.html
src/pretalx/cfp/templates/cfp/event/user_profile.html
src/pretalx/cfp/views/auth.py
src/pretalx/cfp/views/user.py
src/pretalx/cfp/views/wizard.py
src/pretalx/orga/templates/orga/invitation.html
src/pretalx/orga/templates/orga/user.html
src/pretalx/orga/views/settings.py
src/pretalx/person/forms.py
src/pretalx/settings.py
src/pretalx/static/common/scss/_forms.scss
src/pretalx/static/orga/scss/main.scss
src/requirements/production.txt
src/tests/functional/cfp/test_auth.py
src/tests/functional/cfp/test_submission_wizard.py
src/tests/functional/conftest.py

I went through all the occurrences of LoginForms &co (terribly many) to fix scss issues, so we should be good.

Use django-zxcvbn, closes #248

---

doc/install/configure.rst
src/pretalx/common/settings/config.py
src/pretalx/common/settings/utils.py
src/pretalx/settings.py

Okay, I maybe refactored our settings in the progress. So what!

Add email logging option

---

src/pretalx/orga/views/settings.py
src/tests/functional/orga/test_auth.py

[orga] Fix critical invitation token reuse bug

---

.gitignore
src/pretalx/orga/templates/orga/cfp/question_detail.html
src/pretalx/orga/templates/orga/cfp/question_form.html
src/pretalx/orga/urls.py
src/pretalx/orga/views/cfp.py
src/pretalx/submission/models/question.py
src/tests/functional/cfp/test_user.py

Hey guys, please take a look and let me know if I am in the right path. Any feedback will be appreciated. Thank you.
This PR closes/references issue #246 . It does so by …
Adding a button to view and edit question views.

[WIP] [cfp][orga] toggle question visibility

---

src/pretalx/orga/templates/orga/cfp/text.html

display a save button in CfP settings

---

src/pretalx/orga/views/cfp.py

display the right form when adding a question

---

src/pretalx/orga/templates/orga/settings/mail.html

display a save button in mail settings

---

doc/administrator/installation_pip.rst
src/pretalx.example.cfg

changed example cfg paths to /var/pretalx/
added informations to deploy with ubuntu 16.04/debian 9
The change is for all peoply trying to deploy pretalx on a debian / ubuntu system.

Fixed documentation

---

src/pretalx/orga/templates/orga/review/dashboard.html
src/pretalx/orga/templates/orga/submission/state_change.html
src/pretalx/orga/views/submission.py
src/tests/functional/orga/test_submission.py

Redirect back to review list on talk acceptance if came from there

---

src/pretalx/common/models/log.py
src/pretalx/common/templates/common/logs.html
src/pretalx/orga/templates/orga/event/dashboard.html

Hey guys, does it look okay? Or did you have something else in mind?

[WIP] Add links for objects in action logs for Submission and CfP

---

src/pretalx/common/settings/config.py

fix installation crash when there are no config files

---

src/pretalx/orga/views/event.py
src/tests/functional/orga/test_settings.py

Fixes #395 
This should work and has a test, but please tell if it's sane enough :sweat_smile:

[orga] do not allow deletion of last orga member

---

doc/administrator/installation_pip.rst

Is "solves" #419...
/me slap myself hard.

[doc] Add commands to check the logs

---

doc/api/resources/speakers.rst
doc/api/resources/submissions.rst
src/pretalx/api/serializers/speaker.py
src/pretalx/api/serializers/submission.py
src/tests/functional/api/test_api_views.py
src/tests/unit/api/test_serializers.py

Extend API with submission image, speaker avatar and fix speaker biography

Extend API with submission image, speaker avatar and fix speaker biography

---

src/pretalx/cfp/views/event.py
src/pretalx/cfp/views/user.py
src/tests/functional/cfp/test_submission_accept.py

fixes #438
it has automagical tests! :tada:

fix login redirect on loginless speaker talk confirmation

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po

This fixes a typo.
n/a
It was just a typo.

Typo fixed.

---

src/pretalx/orga/templates/orga/settings/team_list.html

Very small PR. This PR adds a "new team" button to the team list so you can create new teams for the orga.

add new team button to team list

---

src/pretalx/common/templates/common/base.html
src/tests/functional/agenda/test_schedule_export.py

hide 404 locale links in HTML export, refs #494

---

src/pretalx/agenda/templates/agenda/schedule.xml
src/pretalx/common/templatetags/xmlescape.py
src/tests/functional/agenda/test_schedule_export.py
src/tests/unit/common/test_common_templatetags.py

fix control characters in submissions breaking frab XML

---

doc/changelog.rst
src/pretalx/orga/forms/mails.py
src/pretalx/orga/views/mails.py
src/tests/functional/orga/test_mail.py

closes #454
using the included tests :)

allow organizers to send an email to all reviewers on the team

---

src/pretalx/locale/fr_FR/LC_MESSAGES/django.po

Hi,
This PR updates the French translation.
The translation has been updated with Poedit which has validated the translation.
NA
Regards,

Update French translation

---

doc/developer/setup.rst

Update the instructions to match the current version of tox.
I followed the updated steps locally.

[doc] Fix "Working with the code" instructions

---

src/pretalx/event/forms.py
src/tests/functional/orga/test_organiser.py
src/tests/unit/orga/test_orga_permissions.py

fix #508 
using the supplied test.. :)

[orga] fix organiser creation, closes #508

---

src/pretalx/cfp/views/user.py

[cfp] fix user in action log for new talk resource

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po

quick fix to german translation

fix sentence negation

---

README.rst

In case, you want to include an additional event using the platform.

NorthSec is using pretalkx

---

src/pretalx/orga/templates/orga/cfp/text.html

This PR closes issue #592 . 
It does so by re-adding the missing line.
user browser test

[orga/cfp] fix missing submit-button

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po

Reveiw → Review
brauchen gute Inhaltsauswahl → brauchen eine gute Inhaltsauswahl
Fix typo
Not.

Fix typo and missing grammatical article

---

README.rst

This PR adds the Tools4AgileTeams Conference to the List of Events using Pretalx.

README: Add Tools4AgileTeams

---

src/pretalx/submission/forms/submission.py
src/tests/cfp/views/test_cfp_wizard.py

fixes #642
via the supplied tests and manually

[cfp] do not show submission types form ALL events in some cases, fix #642

---

src/pretalx/mail/models.py
src/pretalx/submission/models/submission.py

This PR closes/references issue #645 
It attempts to correct the lost newlines in a translation from markdown(?) to html. 
I cannot find the source of the translation, but this is an attempt to fix the issue. 
WIP, Untested

Ensure more correct formatting for full submission content

---

README.rst

The README states
> If you use pretalx for your event, please tell us about it!
We use it, so hereby we tell you about it :wink:

README: added Camp++

---

src/pretalx/submission/models/submission.py

I can try testing this in production :)
Closes #665

Do not display resources that have an empty FileField

---

doc/administrator/installation.rst
src/setup.py

Not at all but both are obvious oversights. If there were tests for them I think they would have been caught already. =)

Replace leftover "pretix" references with "pretalx"

---

doc/administrator/installation.rst

This PR closes/references three documentation/installation related issues:
- https://github.com/pretalx/pretalx/issues/675
- https://github.com/pretalx/pretalx/issues/676
- https://github.com/pretalx/pretalx/issues/677
Experiences from my installation on Ubuntu 18.04 just now. Not tested from scratch again nor on another distro.

fix some broken or missing installation instructions

---

README.rst

We migrated from frab and are very happy so far :)
Keep up the awesome work!

README: Add Klimacamp & Degrowth Summerschool

---

src/pretalx/mail/context.py

This PR closes/references issue #705  . It does so by adding `track_name` as a template key

Add track_name to email template

---

doc/_themes/pretalx_theme/header.html

Looks like the url of the pricing page changed.

Fixed a deadlink

---

src/pretalx/agenda/templates/agenda/schedule.html
src/pretalx/agenda/views/schedule.py
src/pretalx/common/templates/common/base.html
src/pretalx/static/common/js/time.js
src/pretalx/static/common/scss/_pretalx.scss

[agenda] show present time in public schedule

---

src/pretalx/agenda/templates/agenda/schedule.html
src/pretalx/static/common/js/time.js

update "current talk"-highlight in public schedule via javascript

---

README.rst

This PR adds the pretalx schedule for deRSE19 to the list of conferences in [README.rst](README.rst).
Tested link presentation and functionality in the preview when editing README.rst.

Add deRSE19 to list of conferences

---

src/pretalx/schedule/models/availability.py

This PR fixes an internal documentation bug.
By applying logical thinking while stealing^Wtaking inspiration from code.

[schedule] Fix incorrect documentation of overlaps() parameter

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po

No testing needs to be done since merely the string was change

Fix german translation for speaker/talk search

---

src/pretalx/locale/es_MX/LC_MESSAGES/django.po

Translations update from [Weblate](https://translate.pretalx.com/projects/pretalx/pretalx/) for pretalx/pretalx.

🗺 Added translation for Spanish (Mexico)

---

doc/developer/contributing.rst

There was this link intended in the docs but it was not provided
Build the docs; can also be validated using github rich diff

📚 Add forgotten link to prettier

---

src/pretalx/orga/templates/orga/submission/list.html

Add conditional anonymised title to submissions view

---

src/pretalx/common/templatetags/rich_text.py

Reduce the chances of a parser oops with bad protocols.

🐛 Don't even try to linkify disallowed protocols.

---

src/pretalx/locale/cs/LC_MESSAGES/django.po
src/pretalx/locale/es_MX/LC_MESSAGES/django.po

Translations update from [Weblate](https://translate.pretalx.com/projects/pretalx/pretalx/) for pretalx/pretalx.

🗺 Update Czech and Spanish (MX) translations

---

src/pretalx/mail/default_templates.py

This is simply an edit to default mail template copy, to use the same signoff across mails.
N/A

copyedit in default mail templates

---

src/pretalx/locale/pt_BR/LC_MESSAGES/django.po

Translations update from [Weblate](http://translate.pretalx.com/projects/pretalx/pretalx/) for pretalx/pretalx.

Add Portugese locale

---

src/pretalx/locale/it/LC_MESSAGES/django.po

Translations update from [Weblate](http://translate.pretalx.com/projects/pretalx/pretalx/) for pretalx/pretalx.

Add Italian locale

---

src/pretalx/locale/el/LC_MESSAGES/django.po

This PR completes the greek translation

Completed Greek translation

---

doc/developer/plugins/customview.rst
doc/developer/plugins/plugins.rst

When setting up a new Plugin according to the docs I found some small discrepancies and pieces of missing information. This PR adds or modifies the docs to how I found the steps to work.
Tested when setting up a new Plugin according to the docs

Update Plugin-Authoring Docs

---

src/pretalx/locale/zh_CN/LC_MESSAGES/django.po
src/pretalx/settings.py

This PR aims to include Simplified Chinese translation support. At least 99% of the text has been translated. (This is not an exact value, there might be some omissions.)
All the test cases as well as deployed the project in a local environment. No issues were found.

Add Simplified Chinese Translation

---

doc/administrator/maintenance.rst

This is just a minor fix, so I am not filling the rest of the template because makes no sense.

Fix typo in maintenance.rst

---

src/pretalx/locale/cs/LC_MESSAGES/django.po
src/pretalx/locale/es/LC_MESSAGES/django.po

Translations update from Translate pretalx

---

src/pretalx/cfp/templates/cfp/event/user_submission_discard.html
src/pretalx/cfp/templates/cfp/event/user_submission_edit.html
src/pretalx/cfp/urls.py
src/pretalx/cfp/views/user.py
src/pretalx/submission/models/submission.py
src/tests/cfp/views/test_cfp_user.py

Closes #1374, as the remaining issue is better off in a separate issue

Allow to discard draft proposals

---

doc/administrator/commands.rst
src/pretalx/common/management/commands/init.py

This PR closes issue #1551.
I did not test this.

Add `--noinput` option to `pretalx init`

---

doc/developer/plugins/general.rst
src/pretalx/mail/models.py
src/pretalx/mail/signals.py

This implements #1594
- local dev instance of pretalx

Add plugin hook for sent `QueuedMail`s

---

doc/changelog.rst
src/pretalx/orga/templates/orga/base.html
src/pretalx/orga/urls.py
src/pretalx/orga/views/event.py
src/pretalx/orga/views/typeahead.py
src/pretalx/static/common/scss/_dashboard.scss
src/pretalx/static/orga/js/typeahead.js
src/pretalx/static/orga/scss/_layout.scss
src/tests/orga/views/test_orga_views_event.py

Move event search to side nav

---

src/pretalx/locale/fr_FR/LC_MESSAGES/django.po

Translations update: French

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po
src/pretalx/locale/de_Formal/LC_MESSAGES/django.po
src/pretalx/locale/fr_FR/LC_MESSAGES/django.po

Translations update: French, German

---

src/pretalx/locale/de_DE/LC_MESSAGES/django.po
src/pretalx/locale/de_Formal/LC_MESSAGES/django.po

Translations update: German

---

src/pretalx/submission/models/submission.py
src/pretalx/submission/signals.py
src/tests/cfp/views/test_cfp_wizard.py
src/tests/dummy_signals.py
src/tests/submission/test_submission_model.py

This PR is an alternative to #1884 and fixes #1883

Send submission_state_change signal on create

---

doc/changelog.rst
src/pretalx/agenda/management/commands/export_schedule_html.py

This PR closes/references issue #1900.

Fix HTML export.

---

src/pretalx/locale/pt_BR/LC_MESSAGES/django.po
src/pretalx/locale/vi/LC_MESSAGES/django.po

Translations update: Portuguese, Vietnamese

---

src/pretalx/locale/pl/LC_MESSAGES/django.po
src/pretalx/locale/vi/LC_MESSAGES/django.po

Translations update: Polish, Vietnamese

---

src/pretalx/locale/pl/LC_MESSAGES/django.po

Translations update: Polish

---

src/pretalx/cfp/templates/cfp/event/user_submission_edit.html
src/pretalx/orga/templates/orga/submission/comments.html
src/pretalx/orga/views/submission.py

The permission needed to create comments was not correct.
Also corrected a minor error in the submission edit form (cfp).

Fix permissions: comments could not be created.
