pretalx/pretalx

.gitignore
This adds entries from [github python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) to `.gitignore`. It helps new developers, who might use a different tool chain to get started with this project.
=> add entries from github python.gitignore to .gitignore

src/pretalx/locale/de/LC_MESSAGES/django.po, src/pretalx/orga/templates/orga/settings/room_list.html, src/pretalx/orga/templates/orga/speaker/list.html, src/pretalx/orga/templates/orga/submission/list.html
The room settings currently always display "Rooms", "Speakers" and "Submissions", even if there is just one. This PR introduces pretalx to the word "Room" as well as its German translation.
=> [orga] properly pluralize some nouns in settings

src/pretalx/orga/views/submission.py
When you submit an empty speaker name/mail on `/orga/event/foo/submissions/2/speakers`, the app crashes, because `messages.error` is not called properly. This PR makes it display the desired message properly.
=> [orga] replace stackstrace w/ error message when adding an empty mail to talk

src/pretalx/orga/templates/orga/schedule/index.html, src/pretalx/static/orga/scss/_schedule.scss
The schedule editor already looks great, but the buttons on the top kind of confused me. I tried to give them better names. Please note that this is only a suggestion, feel free to make or request any changes you want :)
=> [orga] try to make the buttons in schedule editor clearer

src/pretalx/agenda/views/schedule.py
Events that are not public yet just display a 404-page for their schedule and main public pages. Talks should be hidden as well, just in case the url is shared somewhere by accident.
=> [agenda] ensure that talks for non-public events are inaccessible via their url

src/pretalx/schedule/models/schedule.py, src/tests/unit/schedule/test_schedule_model.py
fixes the following bug:
```python
>>> event.wip_schedule
<Schedule: None>
>>> event.wip_schedule.freeze('Version 2')
>>> event.wip_schedule
<Schedule: Version 2>
(expected: <Schedule: None>)
```
This should, in theory, also happen with `unfreeze()`, but I am not able to replicated it.
=> [schedule] make sure the wip_schedule cache is refreshed on freeze()

src/pretalx/schedule/models/schedule.py, src/tests/unit/schedule/test_schedule_model.py
This fixes #72. Please refer to the issue for details. It also adds a test or two for `Schedule.unfreeze()`.
=> Fix #72: schedule reset hides talk

src/pretalx/orga/templates/orga/settings/team.html
No more "1 Pending Invitations" or "1 Team Members" on the team page! 🎉
=> [orga] pluralize lists on team page

src/pretalx/orga/templates/orga/settings/team.html, src/pretalx/orga/templates/orga/submission/speakers.html, src/pretalx/static/orga/scss/main.scss
This takes the existing layout and iconography  of the team to style the talk speakers list.
Fixes #86.
=> fix #86 add speaker textbox width

src/pretalx/locale/de/LC_MESSAGES/django.po, src/pretalx/orga/templates/orga/dashboard.html, src/pretalx/static/orga/scss/_dashboard.scss, src/tests/functional/orga/test_auth.py
The next inside the "New Event" button is all in one line, which can look a little wonky sometimes. Breaking it into two lines looks nicer, in my opinion:
=> [orga] make the "New Event" button on the orga frontpage more consitent

src/pretalx/orga/management/commands/import_frab.py, src/pretalx/schedule/models/schedule.py, src/tests/functional/fixtures/frab_schedule_minimal.xml, src/tests/functional/orga/test_frab_import.py
Events created by frab import do not have a mail address. This makes the import crash. The speaker mail addresses are also set the "name@localhost". Sending mails is therefore pretty useless right now anyway. Even if there were proper email addresses, I'm not so sure about generating mails for imported talks.
This just disables sending emails during import. It also adds a very simple frab import test.
```
File "/home/luto/c3w/pretalx/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
return self.cursor.execute(sql, params)
File "/home/luto/c3w/pretalx/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: …
```
=> Fix frab import

src/pretalx/agenda/urls.py, src/pretalx/cfp/urls.py, src/pretalx/event/models/event.py, src/pretalx/orga/urls.py
See #113 for details :)
Django does not seem to provide an easy way to match slugs within URLs. [The internet](https://stackoverflow.com/questions/31216363/url-pattern-for-alphanumericslug-string-in-django) [recommends](https://stackoverflow.com/questions/23358685/regular-expression-in-url-for-django-slug) to just use an regex for that. So I did. If you know a smarter way, just hit me up and I'll change this around.
The diff is kind of big, because I removed all the duplicate slug-matching from the URLs. This way I only had the replace the regex in three places.
=> fix event slug url matching

src/pretalx/common/css.py, src/tests/unit/common/test_css.py
1. the CSS parser always returns keys in lower-case. Calling `.lower()` on them doesn't do much. Also add this to the testcase.
2. the CSS parser does not support SVG attributes like `fill`. They never survive `stylesheet.valid`. Checking for them will thus always fail, as they are never present.
=> CSS validator nitpicking

src/tests/functional/fixtures/schedule.xsd
=> [tests] schedule.xsd: make sure minutes and seconds are 00-59

src/pretalx/static/agenda/scss/_agenda.scss
The agenda table headers do not line up properly, if one of the room names is too long to fit:
This MR just makes the name wrap:
Is this a smart enough solution or do we want to expand the table? Or cut the name off? Ellipsis do not seem to work with `overflow-wrap`.
=> [agenda] fix agenda table layout for long room names

doc/features.rst
"room availability" is already implemented.
Remove from "planned" list, added wording to the "scheduling" section and fixed a typo on the way
=> remove implemented feature from "planned" list

src/pretalx/orga/templates/orga/base.html, src/pretalx/orga/templates/orga/settings/review.html, src/pretalx/orga/templates/orga/submission/speakers.html
Since the stylesheet for typeahead.js wasn't included on all sites, some instances of the typeahead searches weren't visually pleasing.
This PR closes issue #173. It does so by removing the typeahead.css from two individual places and puts it into the main orga base.html template, so it is included on all orga pages.
I suggest to have a bigger issue to track some sort of "theming" support/plugin?
=> 173 typeahead fix

src/pretalx/agenda/templates/agenda/schedule.html, src/pretalx/agenda/templates/agenda/talk.html
This PR closes issue #176. It does so by adding a "hover" tooltip to the icon and changes it by stacking the font-awesome "video camera" icon with the "banned" icon on top.
=> more visible icon for the "do not record" flag

src/pretalx/cfp/templates/cfp/event/user_submission_edit.html, src/pretalx/cfp/views/user.py, src/pretalx/common/templates/common/logs.html, src/pretalx/orga/views/submission.py, src/pretalx/static/cfp/scss/_layout.scss, src/tests/functional/orga/test_submission.py
Displays log entries in the user's frontend.
=> Add missing action logs and display them

src/pretalx/agenda/management/commands/export_schedule_html.py, src/pretalx/agenda/templates/agenda/talk.html, src/pretalx/agenda/views/htmlexport.py, src/pretalx/agenda/views/schedule.py, src/pretalx/agenda/views/speaker.py, src/pretalx/common/templates/403.html, src/pretalx/common/templates/404.html, src/pretalx/common/templates/500.html, src/pretalx/common/templates/common/base.html, src/pretalx/person/models/profile.py, src/pretalx/settings.py, src/pretalx/static/agenda/scss/_agenda.scss, src/requirements/production.txt, src/tests/functional/agenda/test_schedule_export.py
fixes #127 
`python manage.py build && (cd data/htmlexport; python -m http.server 8008)`
Soon.
as to not get this PR too bloated, some changes will be moved to new issues and new PRs:
This list is up for discussion.
=> static HTML schedule export

src/pretalx/agenda/templates/agenda/schedule.html, src/pretalx/agenda/views/schedule.py, src/pretalx/schedule/models/schedule.py, src/pretalx/submission/models/submission.py, src/tests/unit/schedule/test_schedule_model.py, src/tests/unit/submission/test_submission_model.py
Please, let me know if I am on the right path.
P.S. I couldn't run the tests locally. There is this error coming up: `You have offline compression enabled but key "1354bed19bb78fa1bb9f122d6ee27708" is missing from offline manifest. You may need to run "python manage.py compress".` Running "python manage.py compress" did not help. Any ideas how I can fix it?
This PR closes/references issue #281 . 
1. Release multiple schedules. Go to an old version. None of the talks should have a link.
2. Delete some submission. It should be displayed as "[deleted]"
=> [WIP] Remove links to talk pages from old schedule views

src/pretalx/agenda/urls.py, src/pretalx/agenda/views/schedule.py, src/pretalx/schedule/models/schedule.py, src/tests/conftest.py, src/tests/functional/agenda/test_agenda_schedule.py
=> move version in schedule URLs from querystring to urlpath

src/pretalx/agenda/__init__.py, src/pretalx/agenda/management/commands/export_schedule_html.py, src/pretalx/agenda/tasks.py, src/pretalx/api/serializers/event.py, src/pretalx/common/models/settings.py, src/pretalx/event/models/event.py, src/pretalx/orga/forms/event.py, src/pretalx/orga/templates/orga/schedule/base.html, src/pretalx/orga/templates/orga/schedule/export.html, src/pretalx/orga/templates/orga/schedule/index.html, src/pretalx/orga/templates/orga/settings/form.html, src/pretalx/orga/urls.py, src/pretalx/orga/views/schedule.py, src/pretalx/schedule/models/schedule.py, src/tests/conftest.py, src/tests/functional/agenda/test_schedule_export.py, src/tests/unit/api/test_serializers.py
Fixes #275 
Refs #277
By frantically clicking around. Real tests will follow.
=> Orga schedule export

CHANGELOG.rst, src/pretalx/agenda/templates/agenda/speaker.html, src/pretalx/agenda/urls.py, src/pretalx/agenda/views/speaker.py, src/pretalx/person/models/profile.py, src/tests/functional/agenda/test_schedule_export.py
Refs #67 
Using the automated tests provided, as well as clicking the new button in the speaker profile manually and importing the resulting file in my calendar.
=> add ical file for all talks of a speaker

src/pretalx/agenda/urls.py, src/pretalx/agenda/views/htmlexport.py, src/pretalx/settings.py, src/pretalx/submission/models/submission.py, src/tests/functional/agenda/test_schedule_export.py
This PR closes/references issue #280 . It does so by …
Adding views in src/pretalx/agenda/views/htmlexport.py
Hey guys, I had a lot of trouble with feed.xml (BuildableFeed). I was able to generate it but in the wrong place and it broker everything else 😅 I did everything else though. Maybe someone else with more experience in this project can take up the feed.xml.
If all look OK, I will try to add tests. Thanks.
=> [agenda] add xml, json, ical, xcal export views

src/pretalx/common/middleware/event.py, src/tests/functional/orga/test_cfp.py
This PR references issue #372. It does so by prioritizing event timezone over user timezone in the backend.
Manually and with a regression test. I'm not sure if it fixes the original problem of #372 as I can't reproduce that one locally.
=> [common] Refs #372 -- Swap priorities of timezone selection

src/pretalx/orga/views/submission.py
Limits access to submissions details via the organizer frontend to organizers and reviewers only.
Tested on a local pretalx install, and shouldn't impact any other parts of the application.
=> Fixed permissions for access to submissions via the organizers frontend

src/pretalx/orga/views/submission.py
Submissions with two speakers show up in the submission list twice, but *only* if the the list is filtered (using any of the available filters). This happens because by searching in ``speakers__name__icontains``, Django creates SQL that SELECTs not only from the submission table, but makes a cross product with the speakers table.
In this case, a simple ``distinct()`` is luckily sufficient to fix it.
Manually.
=> [orga] Avoid duplicate listing of submissions

src/pretalx/event/models/event.py, src/tests/conftest.py, src/tests/functional/agenda/test_schedule_export.py, src/tests/functional/orga/test_frab_import.py, src/tests/functional/orga/test_schedule.py, src/tests/unit/schedule/test_availabilities_mixin.py
Parts of the test suite currently rely on database quirks like auto-incrementing-columns starting at 1 in every test, natural ordering, etc. These tests fail on PostgreSQL, where those assumptions are not true.
Manually by running the test suite with PostgreSQL. We should make this automatic with #388.
=> Make all tests run on PostgreSQL

doc/api/resources/talks.rst, src/pretalx/api/urls.py, src/pretalx/api/views/submission.py, src/tests/functional/api/test_api_views.py
The behaviour of the talks API was inconsistent with the documentation and inconsistent with between different databases. This PR fixes both inconsistencies.
With a regression test.
=> Fix issues in the talks API

doc/administrator/installation_docker.rst, doc/administrator/installation_pip.rst, src/pretalx/schedule/migrations/0001_initial.py, src/pretalx/schedule/migrations/0010_auto_20171001_1358.py, src/pretalx/schedule/models/schedule.py, src/pretalx/settings.py
Schedule.version allows for 200 characters and has a UNIQUE index. However, on MySQL, ~190 characters are at most allowed for indexed fields with 4-byte utf8 support, since 4*190=767 and 767 bytes are their limit for indexed data.
This PR fixes this issue as well as changing the docs to instruct users to use ``utf8mb4`` which fully supports Emojis.
For the tests to pass on MySQL, merging #389 as well is required.
We might want to make the change to settings.py configurable since [converting an existing database](https://mathiasbynens.be/notes/mysql-utf8mb4) isn't trivial and I haven't tested what happens if you run this with a non-mb4 database.
=> Fixes on MySQL

doc/developer/setup.rst
7c97891b moved `src/requirements/production.txt` to `src/requirements.txt`.
The development setup instructions do not reflect this change, resulting in an error during dependency installation:
```Could not open requirements file: [Errno 2] No such file or directory: 'requirements/production.txt'```
Updated command runs without error.
The other boxes don't apply, IMO.
=> [doc] update dev setup guide for moved requirements file

src/pretalx/cfp/templates/cfp/event/user_submission_edit.html, src/pretalx/orga/forms/event.py
This PR changes two user facing placeholders which use domains that are registered by other companies and so shouldn't be used as examples. To solve the problem I changed them to example.org like on other parts of the code.
Not needed.
=> Remove public domains as placeholders in user facing code

src/pretalx/orga/views/speaker.py, src/tests/conftest.py, src/tests/functional/orga/test_speaker.py
This PR closes/references issue #442. It does so by showing the speaker's profile even if his only submission has been deleted.
1. Create a submission for a speaker, that didn't have a submission, for example by submitting a new one.
2. For some reason, delete said submission again. You end up with an existing speaker profile, that has 0 submissions.
3. From the list of speakers, click on the speaker's name.
4. Does not 404 and goes to his profile.
Not sure about the formatting of `get_object()` though. 
Also another way of solving this issue would be to not show the speaker with deleted submissions at all. Let me know if this one makes more sense.
=> [orga] don't 404 on speaker profile if speaker's submission has been deleted

src/pretalx/agenda/templates/agenda/schedule.html, src/pretalx/agenda/templates/agenda/sw.js, src/pretalx/agenda/urls.py, src/pretalx/agenda/views/serviceworker.py
This PR closes/references issue #128 . It does so by using service worker with the scope `/<event_name>/schedule/`. 
1. Start the development server.
2. Go to the event schedule page.
3. Switch off the server.
4. Reload the page and see that the schedule page is loaded with no problem even if the server is not started.
Not sure if I put `sw.js` in the right place...
=> [agenda] make schedule available offline with service worker

src/pretalx/locale/de_DE/LC_MESSAGES/django.po
Currently, the review dashboard shows things like
```
9
Reviewer insgesamt
(13 insgesamt)
```
which doesn't give a way what's the difference between the two numbers.
=> Review Dashboard: Clarify German wording

src/pretalx/orga/views/event.py
The go-live page in master crashes when I open it:
```
TypeError at /orga/event/evt/live
object of type 'LazyI18nString' has no len()
File "/home/luto/c3w/pretalx/src/pretalx/orga/views/event.py" in get_context_data
94.         if not self.request.event.cfp.text or len(self.request.event.cfp.text) < 50:
```
I am not sure if that page is final and open to contributions yet, so accept or reject this MR at will :)
manually.
=> fix crash on go-live page, caused by i18n strings not having a len()

src/pretalx/common/mixins/views.py, src/pretalx/orga/permissions.py, src/pretalx/orga/templates/orga/base.html, src/pretalx/orga/templates/orga/event_list.html, src/pretalx/orga/templates/orga/organiser_list.html, src/pretalx/orga/urls.py, src/pretalx/orga/views/auth.py, src/pretalx/orga/views/dashboard.py, src/pretalx/orga/views/person.py, src/tests/functional/orga/test_access.py, src/tests/functional/orga/test_admin_dashboard.py, src/tests/functional/orga/test_auth.py
The admin dashboard currently shows organisers and events in a single list. The sidebar has a link to "organisers", which 404s.
This splits up the list into an event and an organiser list. The sidebar has been reworked to show links to those lists, each of which is only visible, if the users can actually see or do something there.
Manually and using the supplied tests.
=> split admin dashboard into event/organiser list

doc/changelog.rst, src/pretalx/orga/templates/orga/speaker/form.html, src/pretalx/person/models/user.py, src/pretalx/static/cfp/js/profile.js
When a Speaker does not have an avatar image and Gravatar ist disabled, an empty <img>-Tag without a src-Attributes is generated from the template.
Similar, when the Gravatar-Functionality is deactivated, profile.js tries to reset the Avatar's Image-URL to its original value, which is empty in this case.
This results in the broken-image icon being shown in Chrome.
Scenario 1:
- Create a Submission in the Backend
- Open the Speaker view
- The Avatar-Icon is broken
Scenario 2:
- Enable Gravatar, the Gravatar-Icon is shown
- Save
- Disable Gravatar
- The Avatar-Icon is broken
=> hide avatar-image when no avatar is selected and gravatar is disabled

src/pretalx/common/exporter.py
This fixes a bug introduced by commit 497e81c5aa710432a43c26f27c7e74d721997e85.
The first slash is unnecessary because self.event.urls.export starts with a slash. The second slash is unnecessary there is one already. Django fails to route requests with a double slash inside the path (/sotm2019/schedule/export/speakers.csv works but /sotm2019/schedule/export//speakers.csv fails).
The orga/schedule/export view currently contains defect links to the exports.
Current state (rendered HTML):
```html
<h3>Daten-Export</h3>
<ul>
<li>
<a href="//fossgis2019/schedule/export//speakers.csv">
<i class="fa fa-users"></i>
Vortragenden-CSV
</a>
</li>
<li>
<a href="//fossgis2019/schedule/export//schedule.ics">
<i class="fa fa-calendar"></i>
```
With this fix:
```html
<h3>Data Export</h3>
<div class="alert …
```
=> Remove superfluous slashes from Exporter URLs

src/pretalx/static/orga/scss/_layout.scss
On small screens (my notebook 1366x768 px), the search form of the submission and review list is too wide. The form is a flexbox but without `flex-wrap: wrap`. It looks like this:
This pull request enables `flex-wrap: wrap` and sets `margin-left` of the submit button on same value as the form fields.
The changes affect the following templates:
```sh
[michael@michael-probook pretalx]$ grep -n search-form `find -type f -name "*.html"`
./src/pretalx/orga/templates/orga/submission/list.html:49:        <form class="search-form">
./src/pretalx/orga/templates/orga/review/dashboard.html:80:    <form class="search-form">
./src/pretalx/orga/templates/orga/speaker/list.html:17:        <form class="search-form">
./src/pretalx/common/templates/common/search_form.html:4:<form class="search-form"> …
```
=> Enable flex-wrap: wrap for search forms and fix margin of submit button

src/pretalx/common/mail.py
values passed to headers['reply-to'] are not processed in any way and
thus end up in the actual headers just as they are. in the end the
client ends up with a header like:
```
reply-to: ['orga@event.com']
```
which confuses it.
using the reply_to parameter of djangos mail class correctly joins the
python list into a parsable list:
```
Reply-To: orga@event.com, someone@else.com
```
=> [common] do not pass a ['list'] to mail server for reply-to

src/pretalx/settings.py, src/tests/common/test_common_signals.py
While working on a different patch, I had a local test failure on a test that is already skipped on Travis. I found the root cause and fixed it :)
A test that previously failed now passes.
=> Do not consider empty strings in core module configuration

src/pretalx/common/settings/test_settings.py, src/tests/common/test_common_css.py
When working on pretix, I found this speed-up opportunity and thought you might like it too :) On my machine, it gets the pretalx test suite down from around 100 seconds to around 45 seconds, which I think is quite impressive.
The two optimizations are:
* Cache templates in memory during a test run
* Do not compile SCSS during testing
The second is the major speed gain, but of course has the downside of, well, SCSS not being compiled. It would be easily possible to implement caching instead of just disabling it during tests, but I don't think its worth it, since any compilation errors in the SCSS codebase will be found by the ``rebuild`` command that is already run on CI.
With the test suite.
=> Speed up tests by 50% by not compiling SCSS and caching templates

src/pretalx/orga/forms/event.py
Remove the placeholder address in the Email Settings view. 
**Why?**
Previously, if you had no value in this field, the help text would tell you:
> Sender address for outgoing emails. Leave empty to use the default address: noreply@pretalx.com
However, the placeholder for that input field defaults to be your event email. 
The contrast difference in the form and entered value means that it *looks* like you have set a value, but it's actually empty, using the default. (In this example, the first field has no value, only placeholder; the second field has a value)
By removing the placeholder, administrators won't confuse a value for a lack of value. Also, the helptext will be more accurate ("Leave empty" actually has an empty field, with no placeholder)
Mock up of result:
=> Remove placeholder address

tox.ini
Most packages and `venv` symlink python3 to whatever they have installed. This will cover all 3.6+ versions.  The minimal python requirement is clear from the docs and `setup.py` checks for 3.6 so i don't see any risk here... It just makes the dev's life easier...
=> be more python3.x agnostic

doc/administrator/installation.rst
If the configuration in **Step 4** uses a non-sqlite DB, **Step 5** `pip install --user -U pretalx` (before installing the DB driver) will fail. Swap the order in the documentation.
Also add a missing "with" in "pretalx works your choice of database backends".
(TBH i am not a fan of `pip install --user` as it doesn't scale if the user in question runs multiple apps (whether that's a good/bad is another discussion), but i still prefer vanilla venvs dedicated only to the app.)
=> installation fails if configuration does not use sqlite

src/pretalx/event/stages.py
Gather your team link returns 404. Looks like the link changed. I am not sure though. Maybe it is intentional?
=> 🐛  fixed gather your team link

doc/api/resources/submissions.rst
I was not clear as to when the slot field would appear, and now i now I know
I have not. But it is just a docs change,
=> Mention in API docs that slot does not show up til release

src/pretalx/orga/templates/orga/speaker/list.html, src/pretalx/person/models/profile.py
This clarifies some of the language used in columns and (hopefully) removes ambiguity around "talks" on the speakers page.
Related to #757 
Only looking at the table in the browser
=> Clarify column names in speakers page, add accepted(/confirmed) column

src/pretalx/schedule/models/slot.py
This PR closes/references issue #777 . It does so by checking for clashing talks from the same speaker whenever we check a talk for warnings
This has been tested manually.
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
=> add check for speaker clashes

src/pretalx/orga/templates/orga/settings/review.html, src/pretalx/static/orga/js/main.js
When you edit review phases (move them up/down, delete, ...) the browser scroll jumps to the very top after each action because of the form submit. This remembers the scroll position using JS and resets it. Does nothing without JS.
manually
show me how to make nice gifs on linux and I'll provide one ;)
=> ✨ keep the browser scroll from jumping when editing review phases

src/pretalx/orga/forms/mails.py, src/pretalx/orga/views/mails.py
This PR should fix issue #432 to add an option to send an e-mail to all confirmed speakers without any uploaded slides/resources.
Please double check the filter I used in views/mail.py, I set it to also match `state='confirmed'` as otherwise rejected submissions would get e-mailed too.
Existing tests still pass, except two which failed before I made my changes. No additional tests have been added.
Manually tested this by creating a test event with submissions, etc. in the dev environment.
n/a
=> Add option to send e-mail to confirmed speakers without any slides.

src/pretalx/event/models/event.py, src/pretalx/orga/templates/orga/base.html, src/pretalx/orga/templates/orga/submission/feedbacks_list.html, src/pretalx/orga/urls.py, src/pretalx/orga/views/submission.py
This PR references issue #794. It does so by adding a feedback page, where all event related submissions feedbacks are showed and grouped by submission.
Tested by adding a feedbacks to talks and displaying them on the feedback page (see screenshot).
=> Adding tool to monitor feedback. #794

README.rst
I was sad for a moment thinking the developer documentation is gone. Turns out it was just a change in the link :)
=> fix developer documentation link in README

src/pretalx/common/templates/common/auth.html, src/pretalx/static/common/scss/_forms.scss
This PR disables the Two-Column-Layout for the Register/Login-Screen
Testen in Chrome and Firefox on MacOS.
Before:
After:
=> 🎀 do not use two-column layout on mobile

src/pretalx/common/templates/common/auth.html, src/pretalx/static/common/scss/_forms.scss
This PR fixes a ui regression with the orga login introduced in #856
before
after
=> 🎀 fix login width regression introduced in #856

src/pretalx/locale/fr_FR/LC_MESSAGES/django.po
Hi,
This MR updates the French translation.
There is a message in English which doesn't seem relevant, regarding the new (neat) widget:
https://github.com/pretalx/pretalx/blob/5802c2ccf546cf8a9cb21bb8cf79e0cea8b389bd/src/pretalx/orga/templates/orga/settings/widget.html#L18
The "instead of using this page." part implies that the planning is displayed on this page, which is wrong. Shouldn't it be something like "instead of using the planning page in pretalx"? Or am I misunderstanding? In the French translation I've kept the same meaning as in English.
NA
NA
=> 🗺 Update French translation

src/pretalx/agenda/templates/agenda/speaker.html, src/pretalx/cfp/templates/cfp/event/submission_profile.html, src/pretalx/cfp/templates/cfp/event/user_profile.html, src/pretalx/common/templates/common/avatar.html, src/pretalx/orga/templates/orga/speaker/form.html, src/pretalx/person/forms.py, src/pretalx/static/cfp/js/profile.js, src/pretalx/static/cfp/scss/_layout.scss, src/pretalx/static/cfp/scss/main.scss, src/pretalx/static/common/scss/_avatar.scss, src/pretalx/static/orga/scss/_layout.scss, src/pretalx/static/orga/scss/main.scss
This PR cleans up code and UI around the avatar/gravatar selection. In the current master, the code for avatar-selection and -editing exists three times: in `cfp/…/submission_profile.html`, in `cfp/…/user_profile.html` and in `orga/…/speaker/form.html`. The HTML in these three places is slightly different. There is different CSS for this widget for Frontend and Backend.
This PR moves the relevant HTML and CSS into a central snippet unter `commons/…` and includes this from all three places.
Furthermore this PR enhances the user interaction between the avatar- and the gravatar-selection. Especially it
- hides the "broken image" icon when nothing is selected
- renders a local preview of an selected image
- removes an selected image when gravatar is chosen
- removes gravatar when an image is …
=> cleanup & enhance avatar selection gui

doc/developer/plugins/customview.rst
The example of adding a view to the event sidebar navigation used
an outdated django import.
`django.core.urlresolvers` was renamed to `django.urls`.
=> 📚 Fix code example for adding sidebar view

doc/developer/setup.rst
--noinput is a flag for collectstatic.
Without "--" it is recognized as a flag for tox.
Running the former command yielded the following results on my machine:
```
$ tox -e dev manage.py collectstatic --noinput
usage: tox [--version] [-h] [--help-ini] [-v] [-q] [--showconfig] [-l] [-a] [-c CONFIGFILE] [-e envlist] [--devenv ENVDIR] [--notest] [--sdistonly] [-p VAL] [-o] [--parallel--safe-build]
[--installpkg PATH] [--develop] [-i URL] [--pre] [-r] [--result-json PATH] [--hashseed SEED] [--force-dep REQ] [--sitepackages] [--alwayscopy] [-s [val]] [--workdir PATH]
[args [args ...]]
tox: error: unrecognized arguments: --noinput
```
=> 📚 Fix development setup instructions

src/pretalx/orga/templates/orga/settings/team_detail.html, src/pretalx/orga/templates/orga/settings/team_resend.html, src/pretalx/orga/urls.py, src/pretalx/orga/views/organiser.py
This PR closes/references issue #885 . It does so by adding button to the line with the pending invitations, titled "Resend invite". Then add the functionality to a new view. And uses the send method of the TeamInvite Class
Followed each step by hand; I am not good at writing test yet - I took a look at the existing test but I couldn't figure it out
=> ✨Resend Invite #885

doc/changelog.rst, src/pretalx/cfp/templates/cfp/event/submission_base.html, src/pretalx/cfp/templates/widgets/track-select-widget.html, src/pretalx/locale/de_DE/LC_MESSAGES/django.po, src/pretalx/locale/de_Formal/LC_MESSAGES/django.po, src/pretalx/orga/forms/cfp.py, src/pretalx/orga/templates/orga/cfp/track_form.html, src/pretalx/static/cfp/js/trackDescriptions.js, src/pretalx/static/cfp/scss/_layout.scss, src/pretalx/submission/forms/submission.py, src/pretalx/submission/forms/track_select_widget.py, src/pretalx/submission/migrations/0047_track_description.py, src/pretalx/submission/models/track.py
We have [a Conference with Tracks](https://talks.seibert-media.net/tools4agileteams2020/submit/cBrgkI/info/) which are not necessarily self explanatory to submitters.
This PR adds Description-Texts to the Tracks which, when entered, are displayed below the Track-Select-Field when a Track is selected. Also This PR adds a Button with an Info-Icon next to the Track Field which opens a Modal with all Tracks and their Descriptions.
Both Functionalities are only be activated, when Track Descriptions are used and thus be backwards compatible.
This PR fixes #915 
This change has just been tested in the local development environment. I'm counting on the CI-System to report me all my Style- and Code-Mistakes fo fix.
=> Add Feature: Track Descriptions

src/pretalx/orga/templates/orga/submission/base.html
Otherwise, during a anonymous review stage, this link appears, redirecting the reviewer to a page showing the speaker name.
=> Only show the secret public link if can_view_speakers

src/pretalx/agenda/templates/agenda/featured.html, src/pretalx/agenda/views/schedule.py
If someone ends up in the featured talks page when there are no featured talks, the messaging should be consistent.
The "Welcome!" now only appears if there are talks, and the success banner no longer assumes state of the list.
=> Correct empty featured list message

src/pretalx/agenda/templates/agenda/speaker.html, src/pretalx/agenda/templates/agenda/talk.html
A Pull Request in two parts: 
Much consideration was taken to this page, but given the existing translations and layout of the click-through speaker page, the minimal default profile information, just the bio has been added to the talk page.
Previously: the retrieved gravatar was the default 80x80 size, in a `.speaker-avatar` div of width 180
Now: retrieved avatar is 200x200, which is larger than the display size, but is still a useful size for clearer display.
Testing in local instance
See above
=> Improvements to public talk/speaker page

src/pretalx/orga/forms/event.py
When inheriting an event, it was unclear if this event already had a password set up.  Now if there is no password, the password's placeholder will be "Password". If there is a password, the placeholder will be "********" (8 asterisks) these eight asterisks are stored as a global constant for convenient changing
This PR closes/references issue #994. It does so by completing functionality discussed above
User testing.  I created new events and changed the passwords.  I also inherited events that both did and did not have existing passwords.
Mac OSX and venv
I did not notice any other changes in flexibility
=> 🎀 Add placeholder to email settings password field

src/pretalx/schedule/ascii.py
Seems like breaks and non-submissions does not get a newline when being
printed.
$ curl "https://pretalx.com/arch-conf-online-2020/talk/?format=list"
* 14:00 Break - DJ Set in Arch Conf* 15:00 Protecting secrets and se...
* 16:00 Custom Kernels on Edge Devices in 2020, Angad Sharma (en); i...
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> schedule/ascii: Ensure newline in !talk.submission

src/pretalx/agenda/templates/agenda/talk.html
When the date stored in the database for a talk (eg in UTC time) is the day before (eg 1 December 2020), but the talk will actually take place on 2 December 2020 due to the timezone difference, the talk page will display the date of 1 December 2020 instead of 2 December 2020.
This change makes sure the date object doesn't lose it's timezone component by being converted to a simple date object and instead uses a "Y-m-d" formatter to display it.
This fix is only for the talk template: I suggest looking over the template code for places where this is used:
.date|date:"c"
and replace it with:
|date:"Y-m-d"
Code updated on local copy of site and results appear to match expected date display
- [X ] My code follows the code style of this project.
=> Fix display of date on talk page

doc/user/markdown.rst
Our users were adding dots to the End of their URLs, according to the examples, and they did not work.
=> Fix Link-Example

src/pretalx/orga/forms/event.py, src/pretalx/orga/templates/orga/settings/form.html, src/pretalx/static/cfp/scss/_layout.scss
This PR closes issues #1082 & #1084. It does so by fixing help texts for logo and header images in event's settings. Also, we changed  #event-logo height rule to max-height and deleted width rule.
=> Fix help texts and logo's scaling

doc/developer/setup.rst
When running in development mode, the server is using Django's console
email backend and prints mails to stdout instead of sending them via
SMTP.
The mail configuration is also not loaded by `settings.py` leading to the
proposed port setting of 1025 to be ignored, and default settings
showing up in the admin information, which was a bit confusing to me.
Python's debugging SMTP server was still news to me, so I think it is
useful to keep that information around, in case somebody needs to test
interactions via SMTP.
=> 📚 Update section for email in development setup

doc/administrator/configure.rst
I noticed that the port number in the config description is confusing as 6379 is the "normal" port number for redis
I'm also a bit confused by these lines:
https://github.com/pretalx/pretalx/blob/ce106b7b140c0e0f2178bf7387acbedc4c2c809a/doc/administrator/configure.rst#L270-L276
This setting seems to be a boolean, which would mean that a "sensible value" of a string doesn't make any sense.
=> fix redis port number in docs

doc/administrator/configure.rst
related to #1136
When I tried to set up Pretalx yesterday I got stuck for quite some time getting mysterious errors like `ValueError: Redis URL must specify one of the following schemes (redis://, rediss://, unix://)` or `ValueError: Incorrect timezone setting: "Europe/Berlin"`. 
After missing the forest for the trees for some time, I finally noticed that I was always entering `backend = 'redis://127.0.0.1/1'` and similar values in the config file, but python ini files don't need any quotes and in fact then use the quotes as part of the string which makes the error messages really confusing.
So I think this should be made a bit more clear in the docs in case someone else is coming across the same issue.
=> no quotation signs in config file

doc/administrator/installation.rst
`Referrer-Options` should be changed to `Referrer-Policy` (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
=> Fix incorrect HTTP header name

src/pretalx/schedule/exporters.py, src/tests/agenda/test_agenda_schedule_export.py
Followup PR for #1211:
This reverts commit 953ebe8fd3ed315758f889e8ec5b658976ac319a, as the same changes got merged to frab/main today:
https://github.com/frab/frab/pull/871/files#diff-72d3c524a4fe722765a30e6c4c5f2dd184823971a9e83da56521042136893947R18-R22
This PR closes issue #1118
=> Expose room guid in schedule.json

src/pretalx/agenda/templates/agenda/session_block.html
This PR fixes an issue with the `agenda/session_block.html` template when the abstract contains links. The issue arises due to the browser (tested in Firefox and Chromium) trying to fix things up when `<a>` tags contain other `<a>` tags.
Links will now be stripped, which is fine since `session_block` is only used in two other templates (`agenda/schedule_nojs.html` and `agenda/speaker.html`) where it acts as a link to the actual talk page.
The fix has been verified both by looking at the rendered page (see screenshots) and the markup (before, the surrounding `<a>` tag has spawned multiple `<a>` elements at different levels of the hierarchy - now, there is only one surrounding `<a>` element). Using `grep -r session_block *` I have searched for uses of the template and only found those …
=> Fix 'session_block' for abstracts containing links

doc/changelog.rst, src/pretalx/cfp/flow.py, src/pretalx/cfp/forms/cfp.py, src/pretalx/person/forms.py, src/pretalx/static/orga/js/cfp_flow.js, src/pretalx/static/orga/scss/_flow.scss, src/pretalx/submission/forms/submission.py, src/pretalx/submission/models/submission.py, src/tests/orga/views/test_orga_views_schedule.py, src/tests/submission/test_submission_model.py
Help texts are already configureable, and now titles are too, by popular demand!
Open question: The way this feature is currently implemented, on the first CfP config (flow) save, all current field
titles will be saved, just because they are there in the JSON data. This means future updates to the defaults will not
apply to ongoing events. This is a) a feature because organisers can rely on the field names not changing or b) a
problem, because in case of e.g. typos, we can't update those fields for ongoing events. Debate.
=> Allow organisers to configure CfP field titles

src/pretalx/submission/models/cfp.py
Setting avatars to be required had no effect in our instance.
Upon further inspection, i found that while in the settings, the value `"required"` is stored in this case, `is_field_required()` checked for `"require"` (without d) instead.
This PR fixes this typo.
Drawback: While nearly all CfP fields that are required by default use the value `"required"`, the field `"content_locale"` used `"require"` (which this PR also fixes). If this default value has persisted for some users, this field might no longer be required now (didn'tread into the code enough to check if this method is called for all of the CfP form generation).
Now, setting avatars to be required and not filling out that field actually throws a validation error as expected.
=> fix setting a field to required in CfP not having any effect

doc/administrator/maintenance.rst
This switches the command for the `commit` version to use `https` instead of `git`. Using the unsecured `git://` protocol has been disabled in 2021 (per https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git).
=> switch from git to https

doc/changelog.rst, src/pretalx/agenda/views/talk.py, src/pretalx/cfp/flow.py, src/pretalx/cfp/permissions.py, src/pretalx/cfp/templates/cfp/event/submission_base.html, src/pretalx/cfp/templates/cfp/event/user_submission_edit.html, src/pretalx/cfp/templates/cfp/event/user_submissions.html, src/pretalx/cfp/views/user.py, src/pretalx/cfp/views/wizard.py, src/pretalx/locale/ar/LC_MESSAGES/django.po, src/pretalx/locale/ca/LC_MESSAGES/django.po, src/pretalx/locale/cs/LC_MESSAGES/django.po, src/pretalx/locale/de_DE/LC_MESSAGES/django.po, src/pretalx/locale/de_Formal/LC_MESSAGES/django.po, src/pretalx/locale/django.pot, src/pretalx/locale/el/LC_MESSAGES/django.po, src/pretalx/locale/es/LC_MESSAGES/django.po, src/pretalx/locale/es_MX/LC_MESSAGES/django.po, src/pretalx/locale/fr_FR/LC_MESSAGES/django.po, src/pretalx/locale/it/LC_MESSAGES/django.po, src/pretalx/locale/ja_JP/LC_MESSAGES/django.po, src/pretalx/locale/pt_BR/LC_MESSAGES/django.po, src/pretalx/locale/zh_TW/LC_MESSAGES/django.po, src/pretalx/orga/views/dashboard.py, src/pretalx/orga/views/submission.py, src/pretalx/submission/forms/submission.py, src/pretalx/submission/models/submission.py, src/tests/agenda/views/test_agenda_talks.py, src/tests/submission/test_submission_model.py
Closes #672 
Missing features:
=> Add draft submission state

.github/workflows/docs.yml, .github/workflows/style.yml, .github/workflows/tests.yml
fix #1454
This PR closes/references issue #1454. It does so by replacing `enchant` package by `enchant-2`, because the first one is not available in Ubuntu 22.04. Also to prevent future breakage like this, I change the runner from `ubuntu-latest` to `ubuntu-22.04`. It's effectively the same image for now, but it will prevent this from happening in the future.
I was running `make spelling` locally in a container based on Ubuntu 22.04.
=> ci: fix failing documentation spellcheck build

src/pretalx/static/common/scss/_flags.scss
Czech language has ISO 639-1 code of `cs` while the proper flag is associated with the Czech Republic, that is ISO 3166-2 code `CZ`. This is a simple fix to display proper flag for Czech language.
=> Fix Czech language flag

src/pretalx/orga/forms/event.py
Currently, all users editing event settings see the slug field's help text as "Please contact your administrator if you need to change the short name of your event." This commit customizes the slug help text depending on whether the user is an administrator, so that administrators are not asked to contact themselves.
I used a local copy of pretalx to confirm that administrators see the help text "The slug may only contain letters, numbers, dots and dashes" and that non-administrators are asked to contact an administrator.
=> Customize slug help text

src/pretalx/locale/ja_JP/LC_MESSAGES/django.po
Thank you for this awesome application.
This is a small pull request to fix typo in Japanese translation.
内奥 (naiou) seems a typo.
It should be 内容 (naiyou)
N/A
This is a change of translation.
N/A
Question: Is there a corresponding item in the checklist for pull requests that correct typos of translation?
=> Fix typo in Japanese Kanji

src/pretalx/agenda/views/speaker.py
Apparently passing a content-type header to the FileResponse constructor gets overriden at some point, which makes it ship the .svg with application/octet-stream, which prevents Firefox from rendering it.
The FileResponse constructor¹ however accepts a content_type kwarg, which reliably resolves this situation.
[1] https://github.com/django/django/blob/4.2.4/django/http/response.py#L541-L543
Closes: #1558
This PR closes/references issue #1558. It does so by using the `content_type` kwarg of the `FileResponse` constructor.
Tested in production on talks.mrmcd.net with Python 3.9 and gunicorn.
```
*   Trying /run/gunicorn/pretalx:0...
* Connected to localhost (/run/gunicorn/pretalx) port 80 (#0)
> GET /2023/speaker/avatar.svg HTTP/1.1
> Host: localhost
> User-Agent: curl/7.74.0
> Accept: */* …
```
=> Fix avatar content-type in empty_avatar_view

doc/developer/setup.rst
Fixes the dev instructions, you should no longer enter src before installing.
=> docs: package root not under src

src/pretalx/common/management/commands/init.py
I think that `pretalx init` is broken in the `v2023.1.0` release. There's a syntax error, which I fix in this PR, and the behavior of `--noinput` was also broken. I copied it from `createsuperuser` and now it works for me.
=> fix: commands/init.py

doc/developer/setup.rst
Using `devserver --dev` fails for me:
```
__main__.py devserver: error: unrecognized arguments: --dev
```
It works fine without though.
=> docs: correct use devserver

src/pretalx/submission/forms/submission.py
We used the "require access token" to close certain tracks before the whole conference cfp was closed.
After this was done, submitters who wanted to update their proposal were unable to save it unless they also changed the track.
In any case, I think it is logical that you can keep the existing track if you edit a proposal.
Manual test + deployed on live instance. Still need to add a unit test. If you have a suggestion of a similar test I'm willing to do so.
Existing unit tests fail, but that does not seem related.
=> Make sure proposal can keep track if submission is closed

src/pretalx/schedule/models/schedule.py
It's a bit inconsistent to return the speaker code for an availability warning (line 422) and the id for an overlap warning.
somewhat related: it may be a good idea to use different types for both warnings.
=> use speaker code consistently in warnings

src/pretalx/submission/models/resource.py
We currently allow titles up to 200 characters. External url's using the same title will fail in that case. I think we should up it a bit.
eg eg we wanted to link 
https://ftp.fau.de/fosdem/2024/ub4132/fosdem-2024-3152-node-reduction-through-artificial-intelligence-inferences-using-graphology-and-sigmajs-a-case-study-on-hypertextual-conversations-in-freight-train-graffiti-in-the-north-american-region-.mp4
and that fails, even though that admittedly long title is valid as a title in pretalx.
max_length defaults to 200.
https://docs.djangoproject.com/en/5.0/ref/models/fields/#urlfield
=> Allow longer urls

pyproject.toml, src/tests/agenda/test_agenda_schedule_export.py, src/tests/conftest.py, src/tests/fixtures/schedule.json
Continuing the conversation at #1334: VOC has a JSON schema that we can use to comply against a shared set of expectations, instead of being surprised by frab changes.
Currently waiting for changes in the JSON schema.
=> Validate pretalx frab json exports with VOC schema

src/pretalx/person/models/user.py, src/pretalx/schedule/exporters.py
This PR adds a few missing attributes to schedule.json export, including speaker avatars and switching from relative URIs for external assets to absolute URLs. 
* run locally with democon test data (which has no images on event nor speaker/person)
* validated output agains schedule.json json-schema
=> schedule.json extensions

src/pretalx/frontend/schedule-editor/src/components/Session.vue, src/pretalx/orga/templates/orga/schedule/release.html, src/pretalx/orga/views/submission.py, src/pretalx/submission/models/submission.py
This PR is a draft implementation for #1730, and allows scheduling (by creating slots) for talks that are not finally accepted/confirmed, but only pending.
This allows internal time planning for organizers while not yet having to confirm the talk.
Public visibility is not changed.
Manually tested it by moving the states forward & backward
This PR, at the current stage, is intended as an RFC. Open Points:
- in general, would you merge this feature? If yes, I'd clean/finish the PR.
- shall we add a config option to enable this behavior? On or off by default?
- I'm not so happy with the calls of `update_talk_slots()` - maybe this should be called at the end of every Submission Update to reduce complexity?
=> feat (#1730): Allows scheduling of pending accepted/pending confirmed talks

doc/administrator/installation.rst
This fixes some tiny issues related to installation to venv
- package `python3-venv` is necessary on Debian-based distros
- system command `python` usually does not exist on current distros
- pip switch `--user` cannot be used with venvs
- fixup ExecPath in the unitfile
Tested by doing a fresh installation on Ubuntu 24.05.
=> Fixup install docs regarding venv

src/pretalx/cfp/templates/cfp/event/submission_step.html, src/pretalx/static/cfp/js/proposalTabTitles.js
This change was requested in #1761. This allows the proposal title entered into the proposal wizard to become the title of the page. That title is then populated in the browser tab to make identification of multiple proposal submissions easier across the browser.
- Adds the `proposalTabTitles.js` script to the `submission_step.html` template.
- The script takes the server rendered title and breaks it into its component pieces in order to save the translated "create proposal" prompt in the event the user deletes their title from the wizard and the default title needs to be restored.
- When navigating to the proposal wizard it will quickly check for a proposal title that was placed into the wizard by the user session (in the case a user advances to the "Account" step, then navigates back to …
=> [Issue 1761] Add Proposal Title to Tab of Proposal Wizard

src/pretalx/event/migrations/0034_fix_language_codes.py
This PR fixes migration from relatively old pretalx versions, which fails due to a missing dependency (or alternatively, an incorrect check for existence of a class attribute).
This was tested by migrating an old Pretalx instance to a newer one. The migration would fail with the following error:
```
File "pretalx/event/migrations/0034_fix_language_codes.py", line 98, in fix_language_codes
if not cfp.settings or "flow" not in cfp.settings or not cfp.settings["flow"]:
AttributeError: 'CfP' object has no attribute 'settings'
```
Code review / inspection also reveals the issue.
This could alternatively fixed by using code such as
```
if not hasattr(cfp, "settings") or "flow" not in cfp.settings or not cfp.settings["flow"]:
```
in `pretalx/event/migrations/0034_fix_language_codes.py`.
Tests …
=> Add missing migration dependency on submission.0061_cfp_settings for event.0034_fix_language_codes

doc/changelog.rst, src/pretalx/common/management/commands/rebuild.py, src/pretalx/common/settings/test_settings.py, src/pretalx/common/templatetags/vite.py, src/pretalx/settings.py
It's not possible to get `settings._VITE_IGNORE` variable.
It raises error:
```
102     self._setup(name)
103     _wrapped = self._wrapped
--> 104 val = getattr(_wrapped, name)
....
AttributeError: 'Settings' object has no attribute '_VITE_IGNORE'
```
Can be reproduced by:
```
$ python manage.py shell
$ from django.conf import settings
$ settings._VITE_IGNORE
```
This happens due to fact that django [uses dir()](https://github.com/django/django/blob/main/django/conf/__init__.py#L176) function to merge project_settings with global_settings. And dir() does not return non public attributes.
This PR closes/references issue #XX. It does so by …
=> django settings variable can't start with _

src/pretalx/agenda/views/schedule.py, src/tests/agenda/test_agenda_schedule_export.py
Fixes the value of the ETag field, that is currently being stripped by nginx, because it considers its value invalid per RFC2616¹, as it is missing the required quotation marks.
See also https://forum.nginx.org/read.php?2,286645,286647.
[1] https://datatracker.ietf.org/doc/html/rfc2616#section-14.19
cc @johnjohndoe
Tested in production on talks.mrmcd.net.
```
HTTP/1.1 200 OK
Server: gunicorn
[...]
ETag: "08ed860b1ef6cd0578399766e8794c8fbaf02c40"
$ curl https://talks.mrmcd.net/2024/schedule/export/schedule.xml -I
HTTP/2 200 
server: nginx
[...]
etag: "08ed860b1ef6cd0578399766e8794c8fbaf02c40"
$ curl https://talks.mrmcd.net/2024/schedule/export/schedule.xml -I --compressed
HTTP/2 200 
server: nginx
[...]
etag: W/"08ed860b1ef6cd0578399766e8794c8fbaf02c40"
```
=> Add quotes around the schedule ETag value

src/pretalx/cfp/templates/cfp/event/index.html
As an organiser, there is usually little point in going to the CfP, and it it is not very clear you can go to the organiser area by clicking your username(I've had people asking it). This PR proposes to a big button, which is convenient.
- we used this last year for our event
=> Add big button for organiser area if allowed

src/pretalx/submission/forms/submission.py
Closes #1903 
Looks like count/annotate queries do not use the custom object manager.
I've tested this manually only for now.
=> Correctly show number of submissions per track

src/pretalx/common/exceptions.py, src/pretalx/orga/templates/orga/includes/sidebar_nav.html
This PR closes/references issue https://github.com/F30/samaware/issues/5. It does so by wrapping navigation icons in the appropriate `<i class="fa">` tag; the img tag itself already hat the corresponding `class="fa-img"` attribute.
Lacal installation with samaware plugin.
=> Fix line break after SVG icon

src/pretalx/orga/forms/mails.py
The small PR fixes the bs4 deprecation warnings by replacing `findAll()` with `find_all()` The resolves the warnings found in the[ CI logs](https://github.com/pretalx/pretalx/actions/runs/14532991057/job/40776122378#step:12:188):
```python
/home/runner/work/pretalx/pretalx/src/pretalx/orga/forms/mails.py:168: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
for link in doc.findAll("a"):
```
Run the tests in Python 3.12
=> Resolve bs4 deprecation warnings

CONTRIBUTORS, doc/changelog.rst, src/pretalx/orga/templates/orga/speaker/form.html, src/pretalx/orga/templates/orga/speaker/list.html, src/pretalx/orga/templates/orga/submission/speakers.html, src/pretalx/orga/views/speaker.py
This PR closes/references issue #1892. It does so by adding the `Mark speaker as arrived`-button on the speakers detail page and on the speakers tab of the submissions pages of accepted submissions.
The button is only shown if the `orga.mark_speakers_arrived` permission is present. Thus it is in particular not shown when the event is not yet running.
No button is shown when the speaker was already marked as attending. To undo the flag, the user list must be used (which is unchanged). This is to avoid cluttering the UI wit additional buttons when they are typically not needed.
The `SpeakerToggleArrived`-view now redirects to the referring page if the referer is present in the HTTP request or to the speaker details page if the referer is not know.
=> Organisers can now mark speakers as 'arrived' in more places.

src/pretalx/common/middleware/domains.py
In trying to get my head around what `common/middleware/domains.py` does on a local instance of pretalx, I found I was unable to login when using a custom local domain with http, as the CSRF cookie was being set with `secure=True`.
Some debugging made it clear that pretalx's `_set_cookie_csrf` is not actually being called, as the actual function in Django is `_set_csrf_cookie`.
I don't think this has any major impact on deployments as `get_cookie_domain` can only return None or `SESSION_COOKIE_DOMAIN`, and the Django implementation uses `CSRF_COOKIE_DOMAIN`, both of which are set to by the (as far as I can find) undocumented pretalx `site:cookie_domain` config.
It should make local development with http (unsing non-`localhost` hostnames) easier though as Secure won't be set.
I've also …
=> Fix CSRF middleware

doc/developer/setup.rst
The section [Working with the documentation](https://docs.pretalx.org/developer/setup/#working-with-the-documentation) in the developer docs contains code snippets for all major tasks, but does not mention that some snippets need to be executed from a subdirectory.
This PR adds `cd doc/`, so the docs can be built solely by copy-pasting the code snippets.
An alternative would be to add `doc/` to the commands:
* `make html` -> `make --directory doc/ html`
* `sphinx-autobuild . _build/html --port 8001` -> `sphinx-autobuild . doc/_build/html --port 8001`
I tested the changes manually.
Before:
After:
- No, I tested the changes manually
- No, I think the changes are too small to clutter the changelog
=> Developer Docs: Add missing `cd doc`

doc/changelog.rst, doc/developer/plugins/general.rst, src/pretalx/orga/signals.py, src/pretalx/orga/templates/orga/base.html
This is a stripped down proposal for https://github.com/pretalx/pretalx/pull/2017.
This PR only includes the rather leightweight but very generic ``pretalx.orga.signals.html_above_orga_page`` and ``pretalx.orga.signals.html_below_orga_page`` HTML signals.
The signals are sent out to display additional information on all event related orga pages, above or below all other content.
``pretalx.orga.signals.html_above_orga_page`` is intended for important, somewhat urgent messages that should be displayed prominently, such as a warning about an upcoming deadline or a change in the event schedule.
``pretalx.orga.signals.html_below_orga_page``, on the other hand, is intended to show additional information that is not as urgent as the information displayed by the ``html_above_orga_page`` signal, …
=> Allow plugins to inject HTML in orga area

doc/changelog.rst, src/pretalx/orga/views/mails.py
This PR is only a tiny followup to 439f9e936146d97e2376de2448051a428721f940.
(This is strictly speaking not a fix for the `outbox` but rather the `sent` view.)
=> Fix sorting emails by date

src/pretalx/orga/views/organiser.py
This is only a cosmetic change and minor enough that I only tested it manually.
I’d prefer sorting Teams by name (while keeping Teams with permissions for all Events at the top) instead of by ID.
This way, users can control the order of their Teams by choosing appropriate names, without the overhead of using an OrderedModel — which I find unnecessary.
=> Order teams by team name instead of ID.

doc/changelog.rst, src/pretalx/api/serializers/access_code.py, src/pretalx/api/serializers/speaker.py, src/pretalx/orga/forms/cfp.py, src/pretalx/orga/templates/orga/speaker/form.html, src/pretalx/person/forms/profile.py, src/pretalx/person/models/profile.py, src/pretalx/submission/models/access_code.py, src/tests/api/test_api_access_code.py
Internal notes are now available for speaker profiles (#2031) and access codes (#2084).
The notes are only visible to organisers and reviewers.
They can only be accessed in the organizer area or via the API when authenticated.
API `schema.yml` and migrations have _not_ been updated.
This has only been manually tested in the web prowser and `curl` for the API part.
=> Internal notes for speakers and access codes
